const data =[
    {
    name: "Miyako",
    icon: "https://i.ibb.co/r3D55yD/FNI9UAh.png",
    stars: 2,
    position:125,
    pve:3,
    cb:2,
    pvp:3,
    cbRank:"R8-3",
    rankDiff: ["-198 HP",
        "-325 HP Regen",
        "+48 Physical Attack",
        "+8 Physical Defense",
        "+2 Magic Defense",
        "+2 Dodge"],
    comment: "Pudding is the premier physical tank. The only reason why it's not getting SS rank in arena is due to mages melting her right now. Her invul still makes her one of the best tanks",
    source: "princess",
    },
    {
        name: "Rima",
        icon: "https://i.ibb.co/HBR7Mp9/170-w-Fri-Li1.png",
        stars: 1,
        position:105,
        pve:0,
        cb:0,
        pvp:2,
        cbRank:"R8-3",
        rankDiff: ["-315 HP","-15 TP Regen","+35 Physical Attack","+3 Physical Defense ","+4 Magic Defense","+8 HP Drain"],
        comment: "Great PvP unit to be used in combo teams like Rino cannon / Ninon fan. Clumps the enemies together in arena due to late entry to allow AoEs to land on more targets",
        source: "hard",
    },
    {
        name: "Kuka",
        icon: "https://i.ibb.co/hRVCks0/154-m1qc3-YZ.png",
        stars: 2,
        position:130,
        pve:1,
        cb:0,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ["-10 Magic Attack",
            '-3 Physical Defense',
            '-2 Magic Defense',
            '-5 TP Boost',
            '+160 HP',
            '+56 Physical Attack',
            '+300 HP Rege'],
        comment: "The magic tank version of pudding. A solid counter to Tamaki in arena with taunt if you can time it properly.",
        source: "dungeon",
    },
    {
        name: "Jun",
        icon: "https://i.ibb.co/vBKYFcb/jun.png",
        stars: 3,
        position:135,
        pve:4,
        cb:4,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-5 Physical Defense',
            '-12 Magic Defense',
            '-4 HP Drain',
            '+548 HP',
            '+79 Physical Attack',
            '+15 TP Regen'],
        comment: "Currently one of the best mix tanks. Her kit is awesome: she can def shred, heal and MDEF up for EX. UB has dmg absorb. Clan Battle tank of choice due to def shred. Shines in PvP as the premier tank as well.",
        source: "hard",
    },
    {
        name: "Kaori",
        icon: "https://i.ibb.co/JcnNNTk/071-3n-Ptv-EB.png",
        stars: 2,
        position:145,
        pve:2,
        cb:4,
        pvp:2,
        cbRank:"R8-3",
        rankDiff: ['-213 HP',
            '-2 Magic Defense',
            '-560 HP Regen',
            '-3 HP Drain',
            '+102 Physical Attack',
            '+1 Physical Defense',
            '+10 Physical Critical Rate',
            '+25 TP Regen',
            '+12 TP Boost'],
        comment: "Highest dmg output for the first CB or two. Going to pair nicely with def shred units like Makoto and later Jun. Poor in story due to position at the moment but will get better later on.",
        source: "princess",
    },
    {
        name: "Pecorine",
        icon: "https://i.ibb.co/mDj8HM7/178-9-Igs5x-T.png",
        stars: 1,
        position:155,
        pve:1,
        cb:0,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-87 HP',
            '-6 Physical Defense',
            '-4 Magic Defense',
            '+100 Physical Attack',
            '+15 TP Regen'],
        comment: "Free tank. Use her if you don't have other options. Starts to shine at UE (unique equip) release.",
        source: "hard",
    },
    {
        name: "Nozomi",
        icon: "https://i.ibb.co/wMbkXZv/115-e4-DEe-WA.png",
        stars: 3,
        position:160,
        pve:4,
        cb:2,
        pvp:4,
        cbRank:"R7-6",
        rankDiff: ['-5 Physical Defense',
        '-12 Magic Defense',
        '-4 HP Drain',
       '+534 HP',
        '+81 Physical Attack',
        '+15 TP Regen'],
        comment: "Due to her availability from the Dungeon shop, Nozo will reach 5 star relatively easily. Her stun and taunt skills are both great in PvP. Her kit works well in story too. As more tanks are released, she'll move to S but until then 5 star nozo is great.",
        source: "dungeon",
    },
    {
        name: "Makoto",
        icon: "https://i.ibb.co/n6FHWjD/150-t-XW1o-QL.png",
        stars: 3,
        position:165,
        pve:2,
        cb:5,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-497 HP',
            '-7 Magic Defense',
            '-235 HP Regen',
            '+145 Physical Attack',
            '+2 HP Drain',
            '+10 TP Boost'],
        comment: "Def shred is too important. Makoto is a must have for competitive CB. You are missing out 30-40% dmg without her. She is bad in story but gets an A cuz of her PvE usefulness in event bosses.",
        source: "clan",
    },
    {
        name: "Akino",
        icon: "https://i.ibb.co/QrFsmPq/129-Rbt-FJ5h.png",
        stars: 3,
        position:180,
        pve:1,
        cb:0,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-521 HP',
        '-1 Physical Defense',
        '+76 Physical Attack',
        '+15 TP Regen',
        '+8 HP Drain'],
        comment: "Decent early game. Falls off fast.",
        source: "hard",
    },
    {
        name: "Hiyori",
        icon: "https://i.ibb.co/ssvpMLw/005-wtvv-Vrt.png",
        stars: 1,
        position:200,
        pve:1,
        cb:2,
        pvp:0,
        cbRank:"R8-3",
        rankDiff: ['-406 HP',
            '-7 Magic Defense',
            '-560 HP Regen',
            '-3 HP Drain',
            '+158 Physical Attack',
            '+10 Physical Critical Rate',
            '+25 TP Regen',
            '+12 TP Boost'],
        comment: "Had some appearances in the early CBs cuz you can obtain her shards relatively easy to make her 3 star. Quiet until UE.",
        source: "arena",
    },
    {
        name: "Misogi",
        icon: "https://i.ibb.co/L1h0cGW/022-Kba-Fb5r.png",
        stars: 1,
        position:205,
        pve:0,
        cb:0,
        pvp:0,
        cbRank:"-",
        rankDiff: ['-18 Physical Attack',
            '-560 HP Regen',
            '-25 TP Regen',
            '+58 HP',
            '+4 Physical Defense',
            '+2 Magic Defense',
            '+10 Physical Critical Rate',
            '+12 Dodge',
            '+12 TP Boost'],
        comment: "Real bad.",
        source: "arena",
    },
    {
        name: "Tamaki",
        icon: "https://i.ibb.co/rkWMG4C/156-4qq-UTe-A.png",
        stars: 2,
        position:215,
        pve:0,
        cb:2,
        pvp:4,
        cbRank:"R7-6",
        rankDiff: ['-31 Physical Attack',
            '-260 HP Regen',
            '-25 TP Regen',
            '-3 HP Drain',
            '+165 HP',
            '+8 Physical Defense',
            '+3 Magic Defense',
            '+12 Dodge'],
        comment: "Tamaki stall is a very strong arena meta team. Expect its variations to last until Ilya. She also sees some CB play due to TP manipulation and causing bosses to mistime UBs.",
        source: "arena",
    },
    {
        name: "Eriko",
        icon: "https://i.ibb.co/BqHPqj4/103-u-Bp9qxm.png",
        stars: 2,
        position:230,
        pve:0,
        cb:3,
        pvp:0,
        cbRank:"R8-3",
        rankDiff: ['301 HP',
            '-1 Magic Defense',
            '-235 HP Regen',
            '+113 Physical Attack'],
        comment: "Might see some play early if 3 star+ for clan battle. Quiet until UE.",
        source: "hard",
    },
    {
        name: "Kurumi",
        icon: "https://i.ibb.co/RPz95D4/084-x0-Onhf-X.png",
        stars: 1,
        position:240,
        pve:0,
        cb:0,
        pvp:0,
        cbRank:"-",
        rankDiff: ['-7 Magic Defense',
            '-4 HP Drain',
            '+730 HP',
            '+22 Physical Attack'],
        comment: "Some reddit troll said she's top tier and people fell for it... Will be part of stall teams after UE.",
        source: "hard",
    },
    {
        name: "Djeeta",
        icon: "https://i.ibb.co/k9X6XyY/176-la8dqwk.png",
        stars: 3,
        position:245,
        pve:2,
        cb:3,
        pvp:2,
        cbRank:"R8-3",
        rankDiff: ['-201 HP',
            '-1 Magic Defense',
            '-235 HP Regen',
            '+94 Physical Attack',
            '+15 TP Regen'],
        comment: "Useful in the first few CBs but replaced soon unless 4-5 star from amulets.",
        source: "hard",
    },
    {
        name: "Rei",
        icon: "https://i.ibb.co/Yb3Dt8w/017-6-Bqi112.png",
        stars: 1,
        position:250,
        pve:0,
        cb:2,
        pvp:0,
        cbRank:"R8-3",
        rankDiff: ['-64 HP',
        '+21 Physical Attack',
        '+3 Physical Defense',
        '+15 TP Regen',
        '+5 HP Drain'],
        comment: "UE Rei and 6 Star Rei is top meta stuff but until then... benched.",
        source: "hard",
    },
    {
        name: "Shizuru",
        icon: "https://i.ibb.co/dJ0nvHn/161-4h4-R8-GA.png",
        stars: 3,
        position:285,
        pve:2,
        cb:0,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-638 HP',
        '-3 Physical Defense',
        '-1 Magic Defense',
        '-235 HP Regen',
        '+116 Physical Attack',
        '+15 TP Regen',
        '+8 HP Drain'],
        comment: "Her position sucks. Can be used against tamaki / rino / ninon comps in arena. Not bad as sub tank in pos 3 for story. Otherwise, replaced soon.",
        source: "hard",
    },
    {
        name: "Mimi",
        icon: "https://i.ibb.co/VB4396T/079-x-WM3o-Pg.png",
        stars: 2,
        position:360,
        pve:1,
        cb:2,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-7 Magic Defense',
            '-235 HP Regen',
            '-15 TP Regen',
            '+338 HP',
            '+59 Physical Attack',
            '+3 Physical Defense'],
        comment: "Really average at everything for now. Might see play in 3rd team in early CB if high star",
        source: "hard",
    },
    {
        name: "Shinobu",
        icon: "https://i.ibb.co/dbJ5Kkh/124-jyi-E5-Xb.png",
        stars: 2,
        position:365,
        pve:0,
        cb:2,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-609 HP',
        '-1 Physical Defense',
        '+83 Physical Attack',
        '+1 Magic Defense',
        '+6 HP Drain',
        '+10 TP Boost'],
        comment: "Provides some defense shred and also skull daddy to tank some unique mechanics in CB. Needs 3 star ",
        source: "hard",
    },
    {
        name: "Mahiru",
        icon: "https://i.ibb.co/gW0KNLt/134-46-WVy-Bq.png",
        stars: 2,
        position:395,
        pve:0,
        cb:0,
        pvp:0,
        cbRank:"R7-6",
        rankDiff: ['-6 Physical Defense',
            '-9 Magic Defense',
            '-325 HP Regen',
            '+213 HP',
            '+117 Physical Attack'],
        comment: "Real bad.",
        source: "hard",
    },
    {
        name: "Yukari",
        icon: "https://i.ibb.co/26nRPwT/137-xb4e20-F.png",
        stars: 1,
        position:405,
        pve:3,
        cb:2,
        pvp:3,
        cbRank:"R8-3",
        rankDiff: ['-54 Physical Attack',
        '+203 HP',
        '+3 Physical Defense',
        '+9 Magic Defense',
        '+15 TP Regen',
        '+4 HP Drain'],
        comment: "One of the most versatile support units and she's a 1 star base unit with shards from dungeon coins. Get her to 3 star and save coins for 5 later. You might need to make her not too tanky so she can get off UB.",
        source: "dungeon",
    },
    {
        name: "Monika",
        icon: "https://i.ibb.co/cFdTpn6/172-z-G1-IEk-N.png",
        stars: 3,
        position:410,
        pve:1,
        cb:2,
        pvp:4,
        cbRank:"R7-6",
        rankDiff: ['-119 Physical Attack',
        '-40 TP Regen',
        '+332 HP',
        '+7 Physical Defense',
        '+12 Magic Defense',
        '+600 HP Regen',
        '+8 HP Drain'],
        comment: "Premier PvP unit due to speed buff. Can see CB play for last hits and compensation mechanics.",
        source: "arena",
    },
    {
        name: "Ninon",
        icon: "https://i.ibb.co/KX3qc8D/119-j-Lc-Tib-Q.png",
        stars: 3,
        position:415,
        pve:0,
        cb:0,
        pvp:3,
        cbRank:"R8-3",
        rankDiff: ['-784 HP',
        '-9 Physical Defense',
        '-7 Magic Defense',
        '+194 Physical Attack',
        '+2 HP Drain',
        '+10 TP Boost'],
        comment: "Ninon fan comp core with Saren. Multi targetting isn't that great outside of arena at the moment.",
        source: "hard",
    },
    {
        name: "Mifuyu",
        icon: "https://i.ibb.co/ykTRFvC/159-kwcxufe.png",
        stars: 2,
        position:420,
        pve:0,
        cb:0,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-8 Physical Defense',
        '-11 Magic Defense',
        '+115 HP',
        '+127 Physical attack'],
        comment: "Poop.",
        source: "hard",
    },
    {
        name: "Saren",
        icon: "https://i.ibb.co/9hn7GrJ/109-9r-Dku-Ug.png",
        stars: 3,
        position:430,
        pve:2,
        cb:3,
        pvp:3,
        cbRank:"R8-3",
        rankDiff: ['-522 HP',
        '-2 Physical Defense',
        '+76 Physical Attack',
        '+15 TP Regen',
        '+8 HP Drain'],
        comment: "Enables a lot of stuff in PvP and PvE. Charges closest team member for faster UB. Remember to farm her shards starting Day 1.",
        source: "hard",
    },
    {
        name: "Anna",
        icon: "https://i.ibb.co/RpbGThP/041-e-Lt-E7-GS.png",
        stars: 3,
        position:440,
        pve:1,
        cb:1,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-35 TP Regen',
        '-30 HP Recovery Boost',
        '-5 TP Boost',
        '+429 HP',
        '+24 Magic Attack',
        '+8 Physical Defense',
        '+1 Magical Defense',
        '+1 HP Drain'],
        comment: "Can be used for a mage melt PvP team. Needs a lot more to be useful in CB (S Kyaru/UE etc).",
        source: "princess",
    },
    {
        name: "Kokkoro",
        icon: "https://i.ibb.co/rw6WJL0/180-Zc-YCr2h.png",
        stars: 1,
        position:500,
        pve:2,
        cb:3,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-40 Physical Attack',
        '-325 HP Regen',
        '+903 HP',
        '+1 Physical Defense',
        '+1 Magic Defense'],
        comment: "Good in story due to self heal, tank swap, speed buff. Can be used in CB to help tank for damage tank early.",
        source: "hard",
    },
    {
        name: "Rin",
        icon: "https://i.ibb.co/FxXVjbR/099-J1-BVpy-U.png",
        stars: 2,
        position:550,
        pve:1,
        cb:0,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-40 Physical Attack',
        '-325 HP Regen',
        '+902 HP',
        '+1 Physical Defense',
        '+1 Magic Defense'],
        comment: "Will be used in stall comps in PvP later.",
        source: "none",
    },
    {
        name: "Mitsuki",
        icon: "https://i.ibb.co/dQs5JPf/165-h-GY5igu.png",
        stars: 2,
        position:560,
        pve:1,
        cb:4,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-7 Magic Defense',
        '-235 HP Regen',
        '+319 HP',
        '+44 Physical Attack',
        '+3 Physical Defense',
        '+15 TP Regen'],
        comment: "Good PvP and Clan Battle unit initially. AoE def down enables Rino and Ninon. Times well in CB with Shiori and manual Suzuna.",
        source: "dungeon",
    },
    {
        name: "Akari",
        icon: "https://i.ibb.co/qpW9Cy4/027-43c-Ap-Ej.png",
        stars: 2,
        position:570,
        pve:1,
        cb:1,
        pvp:2,
        cbRank:"R7-6",
        rankDiff: ['-185 HP',
        '-35 TP Regen',
        '-5 TP Boost',
        '+64 Magic Attack',
        '+1 Physical Defense',
        '+2 Magic Defense',
        '+30 HP Recovery Boost'],
        comment: "Can be used with the mage melt pvp team as debuffer. Not really used in CB and story much until higher stars. Lifesteal is very nice though.",
        source: "dungeon",
    },
    {
        name: "Yori",
        icon: "https://i.ibb.co/Z1G2wgP/088-r-LW0-T2r.png",
        stars: 1,
        position:575,
        pve:0,
        cb:1,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-197 HP',
        '-1 Physical Defense',
        '-10 Magic Defense',
        '-5 TP Boost',
        '+131 Magic Attack',
        '+1 HP Drain'],
        comment: "High star Yori hits very hard (4-5 star)in PvP. Bad otherwise.",
        source: "clan",
    },
    {
        name: "Arisa",
        icon: "https://i.ibb.co/QfZPYnw/arisa.png",
        stars: 3,
        position:625,
        pve:3,
        cb:4,
        pvp:3,
        cbRank:"R8-3",
        rankDiff: ['-228 HP',
        '-3 Physical Defense',
        '-1 Magic Defense',
        '-205 HP Regen',
        '+105 Physical Attack',
        '+5 TP Boost'],
        comment: "One of the better bow users on release. Upgrade to Suzuna / Shiori for the first few CBs. Also mainly cuz you can use the other 2 bow users on another team. Decent in arena too.",
        source: "none",
    },
    {
        name: "Rino",
        icon: "https://i.ibb.co/w7N5Ltq/050-Wa-Bh9-AQ.png",
        stars: 3,
        position:700,
        pve:2,
        cb:0,
        pvp:3,
        cbRank:"R8-3",
        rankDiff: ['-23 Physical Attack',
        '-5 Magic Defense',
        '-205 HP Regen',
        '+104 HP',
        '+5 Physical Defense',
        '+12 Dodge',
        '+5 TP Boost'],
        comment: "Rino cannon is potent in PvP at 4+ stars. S rank only if 3 star.",
        source: "arena",
    },
    {
        name: "Suzuna",
        icon: "https://i.ibb.co/R3czvQk/067-j-ZWl-GNw.png",
        stars: 2,
        position:705,
        pve:3,
        cb:4,
        pvp:1,
        cbRank:"R8-3",
        rankDiff: ['-292 HP',
        '-7 Physical Defense',
        '-205 HP Regen',
        '+112 Physical Attack',
        '+2 Magic Defense',
        '+5 TP Boost'],
        comment: "Will shine in CB at launch. Needs manual to maximize damage against bosses to match def shred and also in story mode.",
        source: "princess",
    },
    {
        name: "Shiori",
        icon: "https://i.ibb.co/8NLRMb6/143-Xu9-QCv-H.png",
        stars: 2,
        position:710,
        pve:3,
        cb:4,
        pvp:2,
        cbRank:"R8-3",
        rankDiff: ['-226 HP',
        '-3 Physical Defense',
        '-1 Magic Defense',
        '-205 HP Regen',
        '+105 Physical Attack',
        '+5 TP Boost'],
        comment: "Comparable damage to Suzuna in the long run. Going to be top tier CB unit on launch.",
        source: "hard",
    },
    {
        name: "Io",
        icon: "https://i.ibb.co/FxP311L/076-k-J5z-G3-J.png",
        stars: 3,
        position:715,
        pve:1,
        cb:0,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-4 Magic Attack',
        '-35 TP Regen',
        '-15 HP Recovery Boost',
        '-5 TP Boost',
        '+340 HP',
        '+11 Physical Defense',
        '+3 Magic Defense',
        '+1 HP Drain'],
        comment: "Good in PvP as control + mage melt. Can be used to prevent tamaki UB before Nozo taunt. Can be decent in story early. Bad in other PvE modes.",
        source: "clan",
    },
    {
        name: "Suzume",
        icon: "https://i.ibb.co/zXdjy4x/096-GPp9-Hm5.png",
        stars: 1,
        position:720,
        pve:0,
        cb:0,
        pvp:0   ,
        cbRank:"R7-6",
        rankDiff: ['-26 Physical Attack',
        '-3 Physical Defense',
        '-5 TP Boost',
        '+77 HP',
        '+35 Magic Attack',
        '+5 Magic Defense',
        '+30 HP Recovery Boost'],
        comment: "Poop again.",
        source: "clan",
    },
    {
        name: "Karyl",
        icon: "https://i.ibb.co/KGvKc8b/182-Jrj-Wn-Sz.png",
        stars: 1,
        position:750,
        pve:1,
        cb:1,
        pvp:2,
        cbRank:"R7-6",
        rankDiff: ['-97 HP',
        '-1 Physical Defense',
        '-1 Magic Defense',
        '-35 TP Regen',
        '-5 TP Boost',
        '+86 Magic Attack',
        '+1 HP Drain',
        '+15 HP Recovery Boost'],
        comment: "Decent damage if coined to high stars. Slightly above average performance at 5 stars. Better in later patches.",
        source: "dungeon",
    },
    {
        name: "Hatsune",
        icon: "https://i.ibb.co/dg0s9tH/054-Yv-BLASY.png",
        stars: 3,
        position:755,
        pve:2,
        cb:1,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-103 Magic Attack',
        '-35 TP Regen',
        '-30 HP Recovery Boost',
        '-5 TP Boost',
        '+771 HP',
        '+17 Physical Defense',
        '+12 Magic Defense',
        '+1 HP Drain'],
        comment: "Premier PvP Mage. Also first event shard receipient so you can 4-5 star her relatively quickly. Snipes highest enemy physical attacker.",
        source: "princess",
    },
    {
        name: "Misaki",
        icon: "https://i.ibb.co/6bbNPm8/163-t-RK7j-Kb.png",
        stars: 1,
        position:760,
        pve:0,
        cb:0,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-97 HP',
        '-2 Physical Defense',
        '-1 Magic Defense',
        '-35 TP Regen',
        '-5 TP Boost',
        '+86 Magic Attack',
        '+1 HP Drain',
        '+15 HP Recovery Boost'],
        comment: "Some success in PvP if 3+ stars. Otherwise not used.",
        source: "hard",
    },
    {
        name: "Aoi",
        icon: "https://i.ibb.co/vmtJGRZ/145-ALwm-A00.png",
        stars: 1,
        position:785,
        pve:0,
        cb:0,
        pvp:0,
        cbRank:"R8-3",
        rankDiff: ['-156 HP',
        '-7 Magic Defense',
        '-205 HP Regen',
        '+37 Physical Attack',
        '+12 Dodge',
        '+5 TP Boos'],
        comment: "Bad.",
        source: "hard",
    },
    {
        name: "Chika",
        icon: "https://i.ibb.co/fpvqSCr/148-eh0v-VC8.png",
        stars: 2,
        position:790,
        pve:2,
        cb:1,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-200 HP',
        '-35 TP Regen',
        '-5 TP Boost',
        '+64 Magic Attack',
        '+1 Physical Defense',
        '+2 Magic Defense',
        '+30 HP Recovery Boost'],
        comment: "Great in VH tower and Map push early. Can summon a spirit to tank or eat skills. In PvP, the spiriti is free TP.",
        source: "clan",
    },
    {
        name: "Maho",
        icon: "https://i.ibb.co/9yvpRcs/044-r7-LWef-P.png",
        stars: 3,
        position:795,
        pve:3,
        cb:1,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-26 Physical Attack',
        '-3 Physical Defense',
        '-5 TP Boost',
        '+75 HP',
        '+35 Magic Attack',
        '+5 Magic Defense',
        '+30 HP Recovery Boost'],
        comment: "Great single target burst heal and blind for PvP and PvE. Falls off in terms of heal later on due to AoE healers catching up. Can be used to bait Tamaki.",
        source: "dungeon",
    },
    {
        name: "Yui",
        icon: "https://i.ibb.co/x3vjvNq/010-P0-Ea6ph.png",
        stars: 1,
        position:800,
        pve:3,
        cb:1,
        pvp:1,
        cbRank:"R7-6",
        rankDiff: ['-5 TP Boost',
        '+123 HP',
        '+4 Physical Defense',
        '+4 Magic Defense',
        '+15 HP Recovery Boost'],
        comment: "Good AoE heals and buffs at R7+. Used in VH dungeon boss cheese. Easy to farm shards.",
        source: "hard",
    },
    {
        name: "Yuki",
        icon: "https://i.ibb.co/Scq9hQz/AEbSSVy.png",
        stars: 2,
        position:805,
        pve:1,
        cb:1,
        pvp:3,
        cbRank:"R7-6",
        rankDiff: ['-26 Physical Attack',
        '-5 TP Boost',
        '+240 HP',
        '+20 Magic Attack',
        '+1 Physical Defense',
        '+4 Magic Defense',
        '+15 HP Recovery Boost'],
        comment: "TP charge enabler in PvP. The blind can also come in clutch. Okayish damage for a support.",
        source: "hard",
    },
]



export default data